#!/usr/bin/awk -f

function eval_int(value, parts, count) {
    gsub(/[ ;\r\n\t]/, "", value)
    count = split(value, parts, "+")
    if (count == 2) return parts[1] + parts[2]
    count = split(value, parts, "-")
    if (count == 2) return parts[1] - parts[2]
    return value + 0
}

function rhs(line, parts) {
    split(line, parts, "=")
    return parts[2]
}

BEGIN {
    in_setup = 0
    current = -1
    look = 0
    head_y = 2
    mouth = 0
    eyes = 0
    hand_render = "false"
    hand = 0
    hand_x = 0
    hand_y = 0

    order = "YES_SIR_ANIM YES_SIR3_ANIM UNIT_REPORTING1_ANIM UNIT_REPORTING2_ANIM GRUNTS_REPORTING_ANIM PSYCHOS_REPORTING_ANIM SNIPERS_REPORTING_ANIM TOUGHS_REPORTING_ANIM LASERS_REPORTING_ANIM PYROS_REPORTING_ANIM WERE_ON_OUR_WAY_ANIM HERE_WE_GO_ANIM YOUVE_GOT_IT_ANIM MOVING_IN_ANIM OKAY_ANIM ALRIGHT_ANIM NO_PROBLEM_ANIM OVER_N_OUT_ANIM AFFIRMATIVE_ANIM GOING_IN_ANIM LETS_DO_IT_ANIM LETS_GET_EM_ANIM WERE_UNDER_ATTACK_ANIM I_SAID_WERE_UNDER_ATTACK_ANIM HELP_HELP_ANIM THEYRE_ALL_OVER_US_ANIM WERE_LOSEING_IT_ANIM AAAHHH_ANIM FOR_CHRIST_SAKE_ANIM YOURE_JOKING_ANIM TARGET_DESTROYED_ANIM BLINK_ANIM WINK_ANIM SURPRISE_ANIM ANGER_ANIM GRIN_ANIM SCARED_ANIM EYES_LEFT_ANIM EYES_RIGHT_ANIM EYES_UP_ANIM EYES_DOWN_ANIM WHISTLE_ANIM LOOK_LEFT_ANIM LOOK_RIGHT_ANIM SALUTE_ANIM THUMBS_UP_ANIM YES_SIR_SALUTE_ANIM GOING_IN_THUMBS_UP_ANIM FORGET_IT_ANIM GET_OUTTA_HERE_ANIM GOOD_HIT_ANIM NO_WAY_ANIM NICE_ONE_ANIM OH_YEAH_ANIM GOTCHA_ANIM SMOKIN_ANIM COOL_ANIM WIPE_OUT_ANIM TERRITORY_TAKEN_ANIM FIRE_EXTINGUISHED_ANIM GUN_CAPTURED_ANIM VEHICLE_CAPTURED_ANIM GRENADES_COLLECTED_ANIM"
    count = split(order, names, " ")
    for (i = 1; i <= count; i++) ids[names[i]] = i - 1
}

/void ZPortrait::SetupFrames\(\)/ { in_setup = 1; next }
/int ZPortrait::GetBlitInfo/ { in_setup = 0 }
!in_setup { next }

/cur_anim = &anim_info\[/ {
    name = $0
    sub(/^.*anim_info\[/, "", name)
    sub(/\].*$/, "", name)
    current = (name in ids) ? ids[name] : -1
    next
}

/new_frame.duration =/ {
    value = rhs($0)
    sub(/\*.*/, "", value)
    duration = eval_int(value)
    next
}
/new_frame.look_direction = LOOK_STRAIGHT/ { look = 0; next }
/new_frame.look_direction = LOOK_RIGHT/ { look = 1; next }
/new_frame.look_direction = LOOK_LEFT/ { look = 2; next }
/new_frame.head_y =/ { head_y = eval_int(rhs($0)); next }
/new_frame.mouth =/ { mouth = eval_int(rhs($0)); next }
/new_frame.eyes =/ { eyes = eval_int(rhs($0)); next }
/new_frame.hand_do_render =/ {
    value = rhs($0)
    gsub(/[ ;\r\n\t]/, "", value)
    hand_render = value
    next
}
/new_frame.hand =/ { hand = eval_int(rhs($0)); next }
/new_frame.hand_x =/ { hand_x = eval_int(rhs($0)); next }
/new_frame.hand_y =/ { hand_y = eval_int(rhs($0)); next }

/cur_anim->AddFrame\(new_frame\)/ {
    if (current < 0) next
    hand_x -= 4
    hand_y -= 4
    frame_line = sprintf("    full_frame(%d, %d, %d, %d, %d, %s, %d, %d, %d),\n", duration, look, head_y, mouth, eyes, hand_render, hand, hand_x, hand_y)
    frames[current] = frames[current] frame_line
    frame_counts[current]++
    next
}

END {
    print "// @generated by scripts/generate-portrait-frames.awk from source/zportrait.cpp"
    print "// Source animation ids 0..62; end ids 63..68 alias source sequences in portrait.rs."
    print ""
    for (i = 0; i < 63; i++) {
        printf "const SOURCE_PORTRAIT_ANIMATION_%d: [PortraitFrame; %d] = [\n", i, frame_counts[i]
        printf "%s", frames[i]
        print "];"
        print ""
    }
    print "const SOURCE_PORTRAIT_ANIMATIONS: [&[PortraitFrame]; 63] = ["
    for (i = 0; i < 63; i++) printf "    &SOURCE_PORTRAIT_ANIMATION_%d,\n", i
    print "];"
}
